### ISSUE TITLE
Discussion lacks narrative

### ISSUE THREAD

**Issue by jeromekelleher** [petrelharp/ftprime_ms#67]
The discussion doesn't really have any narrative flow at the moment, and is pretty obviously a collection of things that we didn't know where to put.

1. What do we do with the ana-fits paragraph? We clearly need to say something like this, but it's out of place in the discussion at the moment. Where else could it go? Perhaps at the end of the 'Recording the pedigree forwards in time' section?

2. The parallelisation paragraph is sticking out a bit too. Unless we fill this out with some further discussion about why we'd need to do these large simulations or something, I think we should find a different place for it.

I don't have a concrete idea for the actual narrative of the discussion yet; I thought I'd start the discussion here and see what you guys thought.

**Comment by molpopgen** [comment]
Number 1 could to in intro, as it is part of an overview of existing literature.

For number 2, GWAS-sized samples are one application. And, pop-gen is just getting bigger, at least in some systems.

**Comment by petrelharp** [comment]
Currently, the introduction (1 pg) does:

1. set-up: coal theory and fwds simulation
2. big simulations are still hard
3. recording pedigree and adding neutral muts later might help
4. overview of the paper

and the discussion (1 pg) does:

1. here's what we did
2. previous work: ana-fits (and I propose merging the ARG bit with this)
3. advantages to tree sequences: storage, speed, prior history
4. this is easy to parallelize
5. possible application to phylogenetics
6. "nedigree"

**Comment by ashander** [comment]
"The ARG bit" being this ?
https://github.com/petrelharp/ftprime_ms/blob/60b31af5de68e5f30cba0a25d9b507a0e163c2fc/forwards_paper.tex#L322-L335
good call

**Comment by ashander** [comment]
I guess the alternatives are these:

- in the intro: 3a. to the intro saying anafits and the 08 paper have tried this but are insufficient because X,Y
- in the discussion: merging the ARG bit into 2 to say "the tree sequences are related to ARGs. people have tried to record ARGs but they don't do Z, W"

I'm fine with either.

**Comment by ashander** [comment]
Oh and the phrase "much more limited" in discussing the 08 paper would be nicer if a bit more concrete https://github.com/petrelharp/ftprime_ms/blob/60b31af5de68e5f30cba0a25d9b507a0e163c2fc/forwards_paper.tex#L962-L963

**Comment by petrelharp** [comment]
I like the suggestion of moving prior work to the intro.  I think the reason it ended up in the discussion was because we wanted to contrast what they did to what we do, which is easier after the reader knows what we do.

I could write more about how big simulations are important for the parallelization section.  But, I think the point is fairly tangential: it's in the category of "things I generally want to say" but aren't actually important for this paper.  

**So:** I think my proposal is to move the 'previous work' to the Intro, as Kevin says, and remove the 'parallelization' bit.  Then the discussion would be much more tightly focused.  I'll give this a go in a PR.

**Comment by molpopgen** [comment]
> So: I think my proposal is to move the 'previous work' to the Intro, as Kevin says, and remove the 'parallelization' bit. Then the discussion would be much more tightly focused. I'll give this a go in a PR.

This sounds good.

**Comment by jeromekelleher** [comment]
> So: I think my proposal is to move the 'previous work' to the Intro, as Kevin says, and remove the 'parallelization' bit. Then the discussion would be much more tightly focused. I'll give this a go in a P

+1

**Comment by petrelharp** [comment]
done; thanks all.
