### ISSUE TITLE
typo: rho or r?

### ISSUE THREAD

**Issue by petrelharp** [petrelharp/ftprime_ms#79]
On [this line](https://github.com/petrelharp/ftprime_ms/blob/master/forwards_paper.tex#L277) we say that delterious muts are introduced at rate $\rho/100$, where $\rho = 4Nr$ and $r$ is the per-gamete recombination rate; but (a) that seems wrong, I think it should be $r/100$, and (b) I don't think that's what [the simulations](https://github.com/molpopgen/fwdpy11_arg_example/blob/master/benchmarking.py#L55) are actually doing.

attn: @molpopgen

**Comment by molpopgen** [comment]
It is correct as written.  The scaled rate at which mutation enter is
pdel*rho.  The per-gamete rate at which they enter is pdel*r.  In our sims,
theta=rho, which is why the code matches the description.

I'd have preferred writing this in terms of theta=4Nu, but we aren't
simulating neutral mutations, and so we thought  it would be confusing.

**Comment by petrelharp** [comment]
Hah, of course. =)  Sorry about that.

**Comment by petrelharp** [comment]
Although that line could be clarified to say that it refers to the *total* introduction rate, rather than per-individual.
